### ISSUE TITLE
Ingredients are randomised after world reloads

### ISSUE THREAD

**Issue by ChiefLogan3010** [ssblur/alchimiae#2]
**Mod Version (e.g. Fabric 0.1.0)**: Neoforge 0.2.4-1.21-sdg

**What you expect to happen**:
Discovered ingredients should stay consistent across world/pack reloads.

**What actually happens**:
Ingredients appear to change after reloading the pack or world. For example; before reloading the world sweet berries produced Haste and apples produced Haste & Mining Fatigue, but after reloading both produce Feast & Mining Fatigue.

**Comment by ssblur** [comment]
Thank you for the report, this should be fixed in version 0.2.5.
